import "./globals.css";

export const metadata = {
  title: "Server - Action",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen ">
        <header className="min-h-[10vh]"></header>
        {children}
        <footer className="min-h-[5vh]"></footer>
      </body>
    </html>
  );
}
