import { Providers } from "@/Provider/provider";
import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Broodl",
  description: "Generated by create next app",
};

const elements = {
  header: (
    <header className="p-4 sm:p-8 flex items-center justify-between gap-4">
      <Link href={"/"}>
        <h1 className="textGradient text-xl italic sm:text-3xl font-black ">
          Broodl
        </h1>
      </Link>
      <div className="flex justify-center items-center">
        PLACEHOLDER CTA || STATS
      </div>
    </header>
  ),
  footer: (
    <footer className="p-4 sm:p-8">
      <p className="text-indigo-500 font-bold text-center text-xl">
        Created with ❣️
      </p>
    </footer>
  ),
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full max-width-[1000px] text-sm sm:text-base min-h-screen flex flex-col">
        <Providers>
          {elements.header}
          {children}
          <div className="flex items-center justify-center"></div>
          {elements.footer}
        </Providers>
      </body>
    </html>
  );
}
