import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-screen">
          {" "}
          {/* Ensures full height */}
          <Navbar />
          <main className="flex-1 flex items-center justify-center">
            {" "}
            {/* Centers content */}
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
