import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="root min-h-screen flex flex-col">
          <header className="min-h-[10vh]"></header>
          <main className="flex-1">{children}</main>
          <footer className="min-h-[5vh]"></footer>
        </div>
      </body>
    </html>
  );
}
